# Generated by Django 3.0.6 on 2020-05-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('signup', '0002_auto_20200515_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prof',
        ),
    ]
