# Generated by Django 3.0.6 on 2020-05-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_delete_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posm',
        ),
    ]
